#!/usr/bin/env python3
"""Regenerate markdown report for a run directory."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from qfm.reporting.tearsheet import build_markdown_report, write_report


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate report.md from run artifacts")
    parser.add_argument("--run-dir", default=None, help="Run directory under artifacts/runs")
    return parser.parse_args()


def _latest_run_dir(root: Path) -> Path:
    candidates = sorted([p for p in root.iterdir() if p.is_dir()])
    if not candidates:
        raise FileNotFoundError(f"No run directories found under {root}")
    return candidates[-1]


def main() -> None:
    args = parse_args()
    root = Path("artifacts/runs")

    run_dir = Path(args.run_dir) if args.run_dir else _latest_run_dir(root)
    if not run_dir.exists():
        raise FileNotFoundError(f"Run directory does not exist: {run_dir}")

    metrics_path = run_dir / "metrics.json"
    folds_path = run_dir / "fold_metrics.csv"

    aggregate = json.loads(metrics_path.read_text(encoding="utf-8")) if metrics_path.exists() else {}
    fold_metrics = pd.read_csv(folds_path) if folds_path.exists() else pd.DataFrame()

    report = build_markdown_report(
        run_id=run_dir.name,
        aggregate=aggregate,
        fold_metrics=fold_metrics,
        notes="Generated by scripts/generate_report.py",
    )
    out_path = run_dir / "report.md"
    write_report(out_path, report)

    print(f"Report generated: {out_path}")


if __name__ == "__main__":
    main()
