#!/usr/bin/env python3
"""Run the full walk-forward research pipeline and persist artifacts."""

from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path
import sys

import yaml

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from qfm.data.fetch import (
    DEFAULT_SNAPSHOT_PATH,
    fetch_live_yfinance,
    generate_synthetic_market_data,
    load_snapshot,
    save_snapshot,
)
from qfm.data.preprocess import preprocess_market_data, summarize_market_data
from qfm.factors.mean_reversion import MeanReversionFactor
from qfm.factors.momentum import MomentumFactor
from qfm.factors.volatility import LowVolatilityFactor
from qfm.modeling.walkforward import run_walkforward_research
from qfm.reporting.tearsheet import build_markdown_report, write_report


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run walk-forward factor research")
    parser.add_argument("--config", default="configs/strategy/default.yaml", help="Path to YAML config")
    parser.add_argument("--live", action="store_true", help="Use live yfinance data fetch for this run")
    return parser.parse_args()


def _load_config(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def _get_data(cfg: dict, force_live: bool):
    data_cfg = cfg.get("data", {})
    snapshot_path = Path(data_cfg.get("snapshot_path", str(DEFAULT_SNAPSHOT_PATH)))

    if force_live:
        data = fetch_live_yfinance(
            tickers=data_cfg.get("tickers", ["AAPL", "MSFT", "NVDA", "AMZN", "GOOGL"]),
            start=data_cfg.get("start_date", "2018-01-01"),
            end=data_cfg.get("end_date", "2025-12-31"),
        )
        save_snapshot(data, snapshot_path)
        return data

    if snapshot_path.exists():
        return load_snapshot(snapshot_path)

    # Offline-first fallback: generate deterministic synthetic snapshot.
    data = generate_synthetic_market_data(
        start=data_cfg.get("start_date", "2018-01-01"),
        end=data_cfg.get("end_date", "2024-12-31"),
        tickers=data_cfg.get("tickers"),
        seed=int(data_cfg.get("seed", 42)),
    )
    save_snapshot(data, snapshot_path)
    return data


def main() -> None:
    args = parse_args()
    cfg = _load_config(args.config)

    run_cfg = cfg.get("run", {})
    run_id = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = Path(run_cfg.get("output_root", "artifacts/runs")) / run_id
    run_dir.mkdir(parents=True, exist_ok=True)

    data = _get_data(cfg, force_live=args.live)
    clean_data, preprocess_report = preprocess_market_data(
        data,
        max_ffill_days=int(cfg.get("data", {}).get("max_ffill_days", 3)),
    )

    factor_cfg = cfg.get("factors", {})
    factors = [
        MomentumFactor(
            lookback=int(factor_cfg.get("momentum_lookback", 252)),
            skip=int(factor_cfg.get("momentum_skip", 21)),
        ),
        MeanReversionFactor(
            lookback=int(factor_cfg.get("mean_reversion_lookback", 21)),
        ),
        LowVolatilityFactor(
            window=int(factor_cfg.get("volatility_window", 63)),
        ),
    ]

    research_cfg = cfg.get("research", {})
    result = run_walkforward_research(
        market_data=clean_data,
        factors=factors,
        train_size=int(research_cfg.get("train_size", 504)),
        test_size=int(research_cfg.get("test_size", 126)),
        top_n=int(research_cfg.get("top_n", 20)),
        rebalance_frequency=int(research_cfg.get("rebalance_frequency", 21)),
        transaction_cost_bps=float(research_cfg.get("transaction_cost_bps", 10.0)),
        initial_capital=float(research_cfg.get("initial_capital", 1_000_000)),
    )

    fold_metrics = result["fold_metrics"]
    equity_curve = result["equity_curve"]
    aggregate = result["aggregate"]

    fold_metrics.to_csv(run_dir / "fold_metrics.csv", index=False)
    equity_curve.to_parquet(run_dir / "equity_curve.parquet")

    with open(run_dir / "metrics.json", "w", encoding="utf-8") as handle:
        json.dump(aggregate, handle, indent=2)

    run_snapshot = {
        "config": cfg,
        "data_summary": summarize_market_data(clean_data),
        "preprocess_report": preprocess_report.__dict__,
        "run_id": run_id,
    }
    with open(run_dir / "run_snapshot.json", "w", encoding="utf-8") as handle:
        json.dump(run_snapshot, handle, indent=2)

    with open(run_dir / "config_snapshot.yaml", "w", encoding="utf-8") as handle:
        yaml.safe_dump(cfg, handle, sort_keys=False)

    report = build_markdown_report(
        run_id=run_id,
        aggregate=aggregate,
        fold_metrics=fold_metrics,
        notes="Generated by scripts/run_walkforward.py",
    )
    write_report(run_dir / "report.md", report)

    print(f"Run completed: {run_dir}")
    print(f"Mean fold Sharpe: {aggregate['mean_fold_sharpe']:.4f}")
    print(f"Mean fold total return: {aggregate['mean_fold_total_return']:.4f}")
    print(f"Mean fold alpha (annual): {aggregate['mean_fold_alpha_annual']:.4f}")
    print(f"Mean fold information ratio: {aggregate['mean_fold_information_ratio']:.4f}")


if __name__ == "__main__":
    main()
